# Generated by Django 2.1 on 2018-09-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RegNumber',
            fields=[
                ('text', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='nuts',
            name='reg_numb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.RegNumber'),
        ),
        migrations.AddField(
            model_name='cpv',
            name='reg_numb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.RegNumber'),
        ),
    ]
