# Generated by Django 2.1 on 2018-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20180927_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpv',
            name='text',
            field=models.CharField(max_length=10, verbose_name='CPV-kód'),
        ),
        migrations.AlterField(
            model_name='nuts',
            name='text',
            field=models.CharField(max_length=6, verbose_name='NUTS-kód'),
        ),
        migrations.AlterField(
            model_name='regnumber',
            name='text',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Iktatószám'),
        ),
    ]
