# Generated by Django 2.1 on 2018-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20180927_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpv',
            name='text',
            field=models.CharField(max_length=10, null=True, verbose_name='CPV-kód'),
        ),
        migrations.AlterField(
            model_name='nuts',
            name='text',
            field=models.CharField(max_length=6, null=True, verbose_name='NUTS-kód'),
        ),
    ]
