# Generated by Django 2.1 on 2018-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20181211_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='regnumber',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='Beszerzés Tárgya'),
        ),
    ]
