# Generated by Django 2.1 on 2018-09-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpv',
            name='reg_numb',
        ),
        migrations.RemoveField(
            model_name='nuts',
            name='reg_numb',
        ),
        migrations.AddField(
            model_name='regnumber',
            name='cpv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notices.Cpv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regnumber',
            name='nuts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notices.Nuts'),
            preserve_default=False,
        ),
    ]
