# Generated by Django 2.1 on 2018-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_auto_20181211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regnumber',
            name='asker_act',
            field=models.CharField(max_length=50, null=True, verbose_name='Tevékenységkör'),
        ),
        migrations.AlterField(
            model_name='regnumber',
            name='asker_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Ajánlatkérő típusa'),
        ),
    ]
