# Generated by Django 2.1 on 2018-12-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_auto_20181211_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regnumber',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Elnevezés'),
        ),
    ]
